version: "3"
services:
  app: &base
    build: .
    volumes:
      - .:/work/
      - vendor-gems:/work/vendor/gems
    tty: true
    stdin_open: true
  rake:
    <<: *base
    entrypoint: bundle exec rake
volumes:
  vendor-gems:
