#! /usr/bin/env bash
#
#  run as part of CI, see gem-vuild-and-install.yml
#
if [[ $# -lt 2 ]] ; then
  echo "usage: $(basename $0) <output_dir> <platform>"
  exit 1
fi

set -e

OUTPUT_DIR=$1
BUILD_NATIVE_GEM=$2

test -e /etc/os-release && cat /etc/os-release

echo "Building ${BUILD_NATIVE_GEM} gem"

set -u -x

echo "Updating RubyGems system ..."
echo "gem: --no-ri --no-rdoc" > ~/.gemrc

gem update --system 3.3.22

ruby --version
bundler -v

export BUNDLE_WITHOUT=lint:benchmark:debug:test
bundle

bundle exec rake set-version-to-timestamp

if [[ "${BUILD_NATIVE_GEM}" == "ruby" ]] ; then
  echo "Building ruby gem..."
  bundle exec rake gem
else
  echo "Building native gem..."
  bundle exec rake gem:${BUILD_NATIVE_GEM}
fi

./script/test-gem-file-contents pkg/commonmarker*.gem

mkdir -p ${OUTPUT_DIR}
cp -v pkg/commonmarker*.gem ${OUTPUT_DIR}
ls -l ${OUTPUT_DIR}/*
