#! /usr/bin/env bash
#
#  run as part of CI, see gem-vuild-and-install.yml
#
if [[ $# -lt 2 ]] ; then
  echo "usage: $(basename $0) <output_dir> <platform>"
  exit 1
fi

set -e

OUTPUT_DIR=$1
BUILD_NATIVE_GEM=$2

test -e /etc/os-release && cat /etc/os-release

echo "Building ${BUILD_NATIVE_GEM} gem"

set -u -x

echo "Updating RubyGems system ..."
echo "gem: --no-ri --no-rdoc" > ~/.gemrc

gem update --system --no-document

ruby --version
bundler -v

gem install minitest
gem install minitest-reporters
./script/test-gem-file-contents pkg/commonmarker*.gem

mkdir -p ${OUTPUT_DIR}
cp -v pkg/commonmarker*.gem ${OUTPUT_DIR}
ls -l ${OUTPUT_DIR}/*
