#! /usr/bin/env bash
#
#  run as part of CI, see gem-install.yml
#
set -e
set -u -x

if ! command -v cargo &> /dev/null; then
  echo "cargo not found, fetching..."
  curl https://sh.rustup.rs -sSf > rustup.sh
  bash rustup.sh -y
fi
