#!/bin/bash

set -e

if [ -z "$1" ]; then
  BRANCH="master"
else
  BRANCH=$1
fi

echo "Using $BRANCH..."

echo "Checking out cmark-upstream"
echo "---------------------"
cd ext/markly/cmark-upstream
git fetch origin
git checkout $BRANCH && git pull
sha=`git rev-parse HEAD`
cd ../../..
make
cp ext/markly/cmark-upstream/extensions/*.{c,h} ext/markly
cp ext/markly/cmark-upstream/src/*.{inc,c,h} ext/markly
rm ext/markly/main.c
git add ext/markly/cmark-upstream
git add ext/markly/
git commit -m "Update cmark-upstream to $(git config submodule.ext/markly/cmark-upstream.url | sed s_.git\$__)/commit/${sha}"
